# Site settings
title:          FNS-group
description:    "future network and security"
url:            "https://FNS-group.github.io"
timezone:       Asia/Haikou
global_flags:
  enable_homepage_desc: true

# Author
author:
  name:         Daoxu Qin
  url:          https://github.com/FNS-group
  email:        Daoxuq@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
  - _wiki
  - _posts

collections:
  wiki:
    output: true
    permalink: /wiki/:title/

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

components:
  busuanzi:
    enabled: true
    start_date: 2023-07-16

# GitHub metadata (about page)
repos:
  limit: 6    # recommend even number
